"""Domain entities for the Daily Brief.

The narrative is generated by an LLM, but every number it's grounded in
is included alongside it, structured and separate — same principle as
the Research Agent. A user (or a future UI) can always see the exact
figures behind the AI's summary, not just trust the prose.

Deliberately not persisted — recomputed fresh on each request, same as
valuation/risk. Unlike those, this one has a real per-call LLM cost, so
callers should be mindful of how often they hit this endpoint, but the
"don't cache derived data" principle still holds: a brief generated at
9am showing stale prices at 2pm would be actively misleading.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime


@dataclass(frozen=True, slots=True)
class WatchlistPriceMove:
    ticker: str
    current_price: float
    prior_price: float | None  # None if no snapshot exists yet (never monitored)
    change_pct: float | None


@dataclass(frozen=True, slots=True)
class PortfolioBriefSummary:
    portfolio_id: str
    name: str
    total_market_value: float
    total_unrealized_gain_pct: float | None
    largest_position_weight: float | None
    herfindahl_index: float | None


@dataclass(frozen=True, slots=True)
class DailyBrief:
    user_id: str
    generated_at: datetime
    narrative: str
    model_used: str
    unread_alert_count: int
    watchlist_moves: list[WatchlistPriceMove] = field(default_factory=list)
    portfolio_summaries: list[PortfolioBriefSummary] = field(default_factory=list)
